name: Lint Python Code

on:
  pull_request:
    paths:
      - '**/*.py'  # Trigger workflow only when Python files change

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get changed Python files
        id: get_changed_files
        uses: tj-actions/changed-files@v46
        with:
          files: '**/*.py'

      - name: Run pylint
        if: steps.get_changed_files.outputs.any_changed == 'true'
        uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          glob_pattern: ${{ steps.get_changed_files.outputs.all_changed_files }}
          level: warning
          filter_mode: added
          fail_on_error: true
